### ISSUE TITLE
`smbbrokerpush` uses a `CF_HOME` dir that collides with other errands

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/smb-volume-release#10]
Refer to similar issue on NFS [here](https://github.com/cloudfoundry/nfs-volume-release/issues/44).

Errands may fail with the following error upon subsequent deploys when `CF_HOME` is set to the same directory as another errand:

```
           cf version 6.41.0+dd4c76cdd.2018-11-28  
           API endpoint: https://api.sys.maraudon.cf-app.com  
             
             
           API endpoint:   https://api.sys.maraudon.cf-app.com (API version: 2.128.0)  
           Not logged in. Use 'cf login' to log in.  
           FAILED  
           Service account currently logged in. Use 'cf logout' to log out service account and try again. 
```

Steps to reproduce:
- Run `smbbrokerpush` errand followed by `nfsbrokerpush` (this should fail with the above error)

We're feeling pretty confident that this is the root case:
- The NFS errand sets `CF_HOME` to `/var/vcap/bosh/home/cf/.cf` [here](https://github.com/cloudfoundry/smb-volume-release/blob/211fe02b956327a58f44accb9a98ffb258b11ad7/jobs/smbbrokerpush/templates/deploy.sh.erb#L4) as does the [SMB errand](https://github.com/cloudfoundry/smb-volume-release/blob/211fe02b956327a58f44accb9a98ffb258b11ad7/jobs/smbbrokerpush/templates/deploy.sh.erb#L4) (we'll open a separate issue on those repos)
- If you login as a CF UAA **client**, then login as a CF UAA **user**, the CF CLI will throw the above error
- We configure the NFS errand with a user, but the SMB errand with a client which causes the NFS errand will fail

Workaround is to either disable one of the errands or SSH onto the co-located errand VM and run `rm -rf /var/vcap/bosh/home/cf/.cf`.

The way other components avoid this is to create a CF_HOME dir that is unique to their release, e.g. `export CF_HOME=/var/vcap/data/push-apps-manager/`. Could y'all do something similar with SMB errand?

**Comment by julian-hj** [comment]
fixed in 0.2.6
