### ISSUE TITLE
Get `permission denied error` while writing to the share drive

### ISSUE THREAD

**Issue by Kaixiang** [cloudfoundry/smb-volume-release#2]
Hi:

  We've deployed smb-volume-release with the latest CF release and the deploy works, and we've also deployed SMB test server so we can run some test.

  After pushing [pora](https://github.com/cloudfoundry/persi-acceptance-tests/tree/master/assets/pora) and try to write a file into the shared mount, we get an `permission denied error`.

 After some troubleshooting, we noticed we were using bind options like `{"uid":"1000","gid":"1000","username":"smbuser","password":"<redacted>"}`,

it used a different uid/gid from what is used by smbdriver. the [default](https://github.com/cloudfoundry/smb-volume-release/blob/master/jobs/smbdriver/spec#L42) uid/gid used by smbdriver is 2000.

after changing the bind options to below fixed the issue.
`{"uid":"2000","gid":"2000","username":"smbuser","password":"<redacted>"}`,

so our questions are: Is that behavior expected? why do we want uid/gid to be configured by the user? would it be easier just removing this option?

Regard
Kai

**Comment by AbelHu** [comment]
@kaiyang, I think that we can disable the settings for uid & gid because smbdriver must be executed as root user. I added these settings to keep as same as nfsv3driver when I started the project but now it is not required and cannot be changed to other values.

**Comment by julian-hj** [comment]
I manually added a story here : https://www.pivotaltracker.com/story/show/152909936

(not sure what's up with the gitbot integration--I will try re-adding the api token and see what happens)

**Comment by Kaixiang** [comment]
Sounds good, thanks @AbelHu @julian-hj
