### ISSUE TITLE
Submit smb-volume-release to bosh.io

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/smb-volume-release#3]
So it is easy to download release tarballs.

**Comment by julian-hj** [comment]
Hi Mike,

We have this on our backlog already:
https://www.pivotaltracker.com/story/show/152908940

We just need to do a bit of tidying first as the building inspector has called out some minor things he'd like to see fixed before signing off:
https://www.pivotaltracker.com/story/show/156555888

Cheers,
-Julian

**Comment by julian-hj** [comment]
Just like they say in the Prego ad, "it's in there!"
