### ISSUE TITLE
Add support for cf CLI v8

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/smb-volume-release#44]
[cf CLI v7 support was added 2 years ago](https://github.com/cloudfoundry/smb-volume-release/commit/86d2b4f26ef789b044e24d0a3ee8723e3571a53c).

Now v8 is available and the relevant errands should be updated to accept that version of the cf CLI.

**Comment by ifindlay-cci** [comment]
For information, this is currently predicted to be picked up w/c 25th April.
