### ISSUE TITLE
SMB3 Encryption support

### ISSUE THREAD

**Issue by pranaysharmadelhi** [cloudfoundry/smb-volume-release#8]
Does this tile support Encryption in SMB3?

**Comment by julian-hj** [comment]
If I understand it correctly, then support (or not) for SMB3 encryption is determined by the linux kernel version, with support being added in kernel 4.1.  For Ubuntu, that translates to 16.04, which means that **in theory** if you are using the Xenial stemcell (packaged in PAS 2.3) you should get SMB3 encryption.

Let us know if you see different results.

**Comment by julian-hj** [comment]
We recently tested our SMB service on a xenial stemcell connecting to Azure file service and it appears to be working nicely.  Unless I am mistaken, Azure won't accept remote connections unless SMB3 & encryption are working.  I'm going to go ahead and close this issue.  Please feel free to re-open it if you have any problems.
